question_bank = [
    ("Jan says that men love the scent of one of the candles she makes. What's it called?","Bonfire"),
    ("It's the booze cruise. What Gilligan's Island character does Michael tell Pam she is?", "Mary Ann"),
    ("Name one of the three things that Oscar says DMI, Dunder Mifflin's stock symbol, stands for.", "dummies, morons, idiots"),
    ("Dwight dressed up for Casino Night in an heirloom tux. What's the story behind it?","His grandfather was buried in it."),
    ("Someone tells Pam that they'll give her $100 now as a wedding present, or $5,000 in a year. Who's that?", "Ryan"),
    ("Which office worker gets their company bathrobe taken away?", "Toby"),
    ("Ryan's assistant tells him he has a call from Eddie Murphy but it's Michael doing an impression of what movie character?", "Donkey, from Shrek"),
    ("Michael realizes that Dwight doesn't want to be disturbed in his hotel room when he sees this tied to the door knob.", "Dwight's sock"),
    ("Pam and Jim play a prank on Andy that results in Andy punching a hole through a wall. What was the prank?", "Jim put Andy's cell phone in the ceiling."),
    ("They're really going to the hospital but instead, Jim tells Dwight they're going to this restaurant/entertainment place.", "Chuck E. Cheese"),
    ("Angela wants this ailment to be covered by the new health plan.", "dermatitis"),
    ("What is the name of the student at the job fair that Michael first insults, then tries to win over?", "Justin (Polznik)"),
    ("Michael's gossip about Dwight concerns store-bought varieties of this. What is it?", "manure"),
    ("What gift did Stanley buy for Pam and Jim's wedding?", "a toaster"),
    ("Andy tells Angela that one day they'll move here and ''leave this all behind.'' Where do he and Angela want to go?", "Disney's Celebration Village"),
    ("Michael says that this green toy has a better body than Jim.", "Gumby"),
    ("Martin, the ex-con from Stamford, was in jail for this.","Insider Trading"),
    ("Andy wants Pam and Jim to hire his acappella group for the wedding. After playing his demo tape, what song does Andy say Pam will boogie down the aisle to?", "You Can Call Me Al"),
    ("Dwitght: ''A thirty-year mortgage at Michael's age essentially means he's buying'' what?", "a coffin"),
    ("During the break at the shareholders' meeting, Michael says he'll get help from a Mexican guy who knows as much about math as he does about what?", "bullfighting"),
    ("Who said it? ''Oh, Jim Carrey just walked in. Dwight, get his autograph for Michael quickly.", "Phyllis"),
    ("While playing chess, who tells Jim they want to set him up with their daughter?", "Creed"),
    ("What did Ryan remind Creed to organize when the office did spring cleaning in January?", "The menu book."),
    ("In Dwight's perfect crime scenario, he breaks into this jewelery store and steals its chandelier.","Tiffany"),
    ("Stanley takes a break from spring cleaning to get a drink from the vending machine. Michael ends up making the selection for him, though, choosing something he says Stanley's going to hate. What is it?", "Peach iced tea"),
    
]

print(f"Question: {question_bank[0][0]}")