question_bank = [
    ("Jan says that men love the scent of one of the candles she makes. What's it called?","Bonfire"),
    ("It's the booze cruise. What Gilligan's Island character does Michael tell Pam she is?", "Mary Ann"),
    ("Name one of the three things that Oscar says DMI, Dunder Mifflin's stock symbol, stands for.", "dummies, morons, idiots"),
    ("Dwight dressed up for Casino Night in an heirloom tux. What's the story behind it?","His grandfather was buried in it."),
    ("Someone tells Pam that they'll give her $100 now as a wedding present, or $5,000 in a year. Who's that?", "Ryan"),
    ("Which office worker gets their company bathrobe taken away?", "Toby"),
    ("Ryan's assistant tells him he has a call from Eddie Murphy but it's Michael doing an impression of what movie character?", "Donkey, from Shrek"),
    ("Michael realizes that Dwight doesn't want to be disturbed in his hotel room when he sees this tied to the door knob.", "Dwight's sock"),
    ("Pam and Jim play a prank on Andy that results in Andy punching a hole through a wall. What was the prank?", "Jim put Andy's cell phone in the ceiling."),
    ("They're really going to the hospital but instead, Jim tells Dwight they're going to this restaurant/entertainment place.", "Chuck E. Cheese"),
    ("Angela wants this ailment to be covered by the new health plan.", "dermatitis"),
    ("What is the name of the student at the job fair that Michael first insults, then tries to win over?", "Justin (Polznik)"),
    ("Michael's gossip about Dwight concerns store-bought varieties of this. What is it?", "manure"),
    ("What gift did Stanley buy for Pam and Jim's wedding?", "a toaster"),
    ("Andy tells Angela that one day they'll move here and ''leave this all behind.'' Where do he and Angela want to go?", "Disney's Celebration Village"),
    ("Michael says that this green toy has a better body than Jim.", "Gumby"),
    ("Martin, the ex-con from Stamford, was in jail for this.","Insider Trading"),
    ("Andy wants Pam and Jim to hire his acappella group for the wedding. After playing his demo tape, what song does Andy say Pam will boogie down the aisle to?", "You Can Call Me Al"),
    ("Dwitght: ''A thirty-year mortgage at Michael's age essentially means he's buying'' what?", "a coffin"),
    ("During the break at the shareholders' meeting, Michael says he'll get help from a Mexican guy who knows as much about math as he does about what?", "bullfighting"),
    ("Who said it? ''Oh, Jim Carrey just walked in. Dwight, get his autograph for Michael quickly.", "Phyllis"),
    ("While playing chess, who tells Jim they want to set him up with their daughter?", "Creed"),
    ("What did Ryan remind Creed to organize when the office did spring cleaning in January?", "The menu book."),
    ("In Dwight's perfect crime scenario, he breaks into this jewelery store and steals its chandelier.","Tiffany"),
    ("Stanley takes a break from spring cleaning to get a drink from the vending machine. Michael ends up making the selection for him, though, choosing something he says Stanley's going to hate. What is it?", "Peach iced tea"),
    ("Michael tells Jim that kids in high school called him this because he once got it stuck in the power drill.", "Ponytail"),
    ("Jim finds a recording device planted by Dwight. He says if he plays it right he can get Dwight to act out the plot of this 2004 Nicolas Cage-Diane Kruger film.", "National Treasure"),
    ("Michael has been saving checks from his nana. What vehicle did he think he was going to buy with them?", "A motorcycle"),
    ("Angela's working on putting together a last-minute luau. She tells Phyllis to pick up a pig from here.", "a petting zoo"),
    ("Jinx! Jim's not allowed to talk until he buys Pam what soda?", "Coke"),
    ("While Michael attends the shareholder's meeting in New York City, Dwight hopes to buy a couple crates of these.", "shirts"),
    ("In preparing to take over Michael's job as Regional Manager, who is Dwight's first, albeit fictional, choise for his number-two person?", "Jack Bauer"),
    ("What friend does Ryan introduce Michael and Dwight to in the club?", "Troy"),
    ("After Pam and Jim leave the conference room, what does Michael call the wedding site instead of Niagra Falls?", "Viagra Falls"),
    ("Who took a cab with Creed and Stanley during the Fun Run?", "Oscar"),
    ("Dwight applies the oil from what animal to cure Phyllis's back pain?", "otter"),
    ("Kevin is telling everyone to come hear his band, Scrantonicity II. Why does he need as many people to cheer him on as possible?", "The bar uses an applause meter."),
    ("Dwight says he once shot a werewolf, but by the time he got to it, it turned back into this.", "his neighbor's dog"),
    ("What does Michael forbid Angela to do at Cafe Disco?","clean up"),
    ("Both Dunder and Mifflin have the same first name. What is it?", "Robert"),
    ("Dwight has two coins totaling 15 cents. One of them is not a nickel. Then what are they?", "a dime and a nickel (the other coin is a nickel)"),
    ("Why does Phyllis say that the security guard will never come to unlock the gate for the stranded office workers?", "because Jim forgot to collect a Chirstmas tip for him"),
    ("Angela's in despair over her cat's death. Dwight fails to lift her spirits when he reminds her there are three things cats can't provide for people. Name One.", "milk, wool, meat"),
    ("In addition to a three-month paid vacation, what does Oscar get for not suing the company?","a company car"),
    ("Dwight offers what kind of lessons as part of his Secret Santa gift?","paintball lessons"),
    ("Kevin hides his jar of these under his desk when Michael brings ex-Stamford employee Hannah to her new Scranton desk.", "M&Ms"),
    ("Who tells Pam that they'll eat whatever is ''fanciest'' on the wedding menu, unless there's ribs?", "Mereditch"),
    
]

print(f"Question: {question_bank[0][0]}")